version: "3.7"
services:
  helloworldlambda:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:8080"
    volumes:
      - ~/.aws-lambda-rie:/aws-lambda
    entrypoint: ["/aws-lambda/aws-lambda-rie", "/lambda"]